### ISSUE TITLE
RFC: Dymanic Prayer Preview Cards

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/ApollosProject#140]
## Summary
Dynamic prayer preview cards should exist under each of the main categories of prayer. 

## Motivation
The motivation for this is that it's confusing to see a preview for a prayer that doesn't actually exist. When someone sees a prayer preview they expect to see that prayer when they tap "Start Praying". This also keeps the prayer preview card from becoming stale content.

## Detailed Design
The prayer preview card should just pull the first prayer off of the list of prayers for that particular category. 

The big design challenge here is what we do when there are no prayers for a category. Right now, we show a static prayer preview card and then _after_ you tap "Start Praying" we show a `No Prayers` component. I think this should change so that the `No Prayers` component displays in place of the prayer preview card (or this is a second state of the prayer preview card) when there are no prayers. This makes it apparent to a person right away that there are no prayers for that category without the need of a button press in order to find out that information. 

This would also allow us to add a button to the `No Prayers` component that would open the `Add Prayer` modal and allow that person to add a prayer. Obviously, that person's prayer wouldn't show in their list (so their list would still be empty). But it encourages adding prayers. 

## How We Teach This
Nothing to teach. It's just a better experience.

## Drawbacks
Not sure of any. But I'm open to suggestions.

## Alternatives
Perhaps there is a better design?

## Unresolved Questions
Not sure. This seems to cover pretty much all cases I can think of regarding dynamically generating prayer preview cards.

## Note
I created a task for this on Jira (https://newspring.atlassian.net/browse/DEV-3855) but wanted a place to discuss implementation details.

So ... thoughts?

**Comment by FrankGrand** [comment]
@richarddubay Complete agree on the need for this.  We've had multiple people give us feedback that seeing a prayer card for something that isn't there is confusing!

I like the idea of the just pulling the first card.  Engineering wise, maybe if there aren't in prayers in a category, we shouldn't even show the 'parent' option?

**Comment by richarddubay** [comment]
@FrankGrand Not showing the 'parent' option if there are no prayers is an interesting idea. Do you think it would be weird to the person using the app if the menu option were to appear/disappear as prayers were removed/added to a certain category? I don't know that that would be an occasion that happened very often, but it could ... most likely with the community section, I would think. 

I do like that this way of handling it would do away with the need or a `No Prayers` component entirely. That seems like a win to me.
