### ISSUE TITLE
Studies not showing children

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/ApollosProject#86]
When opening up a study, no children is being shown. For example, if I open "Acts 28-Day Reading Guide", there's no child content below it and I can't navigate to the individual devotionals.

Most likely a query issue.

**Comment by redreceipt** [comment]
@conrad-vanl agreed because I get a "Bad Request 400" error when going to the content. Debug question: how can I sniff what request is going to Rock? Is there a way without trying to figure out where in the code it's happening?

**Comment by conrad-vanl** [comment]
If you're running locally the API should be logging the requests that are made. @vinnyjth ?

**Comment by redreceipt** [comment]
https://github.com/ApollosProject/apollos-prototype/issues/729
