### ISSUE TITLE
"Activated" series video not showing

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/ApollosProject#87]
When playing the video on the "Activated" Series content item, the media plays audio but the player is an empty black screen.

Either the player thinks that the content is a video when it's really an audio, or there's a problem with the player not being able to play the video content.

**Comment by redreceipt** [comment]
having trouble reproducing this. @conrad-vanl is this still an issue for you?

<img width="447" alt="Screen Shot 2019-05-30 at 10 59 08 AM" src="https://user-images.githubusercontent.com/2659478/58641856-0b885700-82ca-11e9-92fe-7c84e0642554.png">
